version: '3.8'

services:

  # Qdrant向量数据库
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: hicrm-qdrant
    
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
#      - QDRANT__SERVICE__API_KEY=hicrm
    restart: unless-stopped
    networks:
      - hicrm-network

  # Elasticsearch搜索引擎
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: hicrm-elasticsearch
    environment:
      - node.name=hicrm-es-node
      - cluster.name=hicrm-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    networks:
      - hicrm-network

  # Kibana (可选，用于Elasticsearch管理)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: hicrm-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - hicrm-network

volumes:
  qdrant_storage:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  hicrm-network:
    driver: bridge
